### ISSUE TITLE
Merchant is not redirected to the main Magento CMS index route

### ISSUE THREAD

**Issue by TomashKhamlai** [magento/magespecialist_TwoFactorAuth#6] opened 2018-02-15 16:09 UTC
**Preconditions:**
TwoFactorAuth module is active.
Authy is enabled but not forced

**Steps to reproduce:**
Go to System > Permissions > All Users
Edit your current user
Switch to 2FA section
Tick Authy checkbox to enable it for the current user
Save configuration and log out from Admin
Log in to Magento Admin using Authy authenticator

**Expected result:**
:white_check_mark: Merchant is redirected to Dashboard

**Actual result:**
:x: 404 Error
![actual](https://user-images.githubusercontent.com/11827230/36266885-4c7441ea-127b-11e8-8bda-6b3dc06c8dfe.png)

**Comment by phoenix128** [comment] 2018-02-19 14:56
I am unable to reproduce this. Are you sure you have the latest version?

**Comment by vkublytskyi** [comment] 2018-02-20 16:00
@phoenix128 I was redirected to 404 admin page after forcing google authenticator:
1. enable 2fa,
2. enable Google Authenticator and U2F Devices
3. force Google Authenticator and U2F Devices
4. scan code and enter it for Google Authenticator
5. after this 404 page is displayed

**Comment by TomashKhamlai** [comment] 2018-02-21 16:52
@phoenix128, I tried to navigate to the URL that was used in [#L115](https://github.com/magespecialist/magespecialist_TwoFactorAuth/blob/25a4b555177f8bb62792636e682c88cfa811a024/Observer/ControllerActionPredispatch.php#L115), but it goes to '404' page no matter what kind of authentication was used or even navigating there by typing the URL by hands with secret key disabled.

How it looks:
![peek 2018-02-21 18-14](https://user-images.githubusercontent.com/11827230/36492858-d4628c50-1736-11e8-8d04-46cd081fe1e8.gif)

I don't know if this information will be useful:
We use subfolder for Magento installation (https://subdomain.domain/path/to/subdir_where_magento_is installed/admin/admin/module/controller/action/key/somekey)

**Comment by phoenix128** [comment] 2018-02-25 16:53
Confirmed. It seems to be an issue with M2.2 and M2.3, correctly working on M2.1 . Fixing it.

**Comment by phoenix128** [comment] 2018-02-25 19:00
You have this fixed inhttps://github.com/magento/magespecialist_TwoFactorAuth/pull/1/commits/d2cdc7244f07cb658f9e962e8119f5cb628bde92

**Comment by TomashKhamlai** [comment] 2018-02-28 11:39
Duo Security also has this issue

:white_check_mark: Google Authenticator
:white_check_mark: Authy
:x: Duo Security

**Comment by phoenix128** [comment] 2018-02-28 15:18
Hi @TomashKhamlai ,
Seems like I forgot a couple of files in my last commit.

Fixed in: https://github.com/magento/magespecialist_TwoFactorAuth/pull/1/commits/5162123653bd06b56a62578e81a6120d2d3d5f8f

**Comment by vkublytskyi** [comment] 2018-03-06 08:55
Fixed

**Closed by vkublytskyi** 2018-03-06 08:55 UTC
